WITH FLARE AS (
SELECT 
    PROPERTY_NAME,
    PROPERTY_ID,
    BASIN_NAME,
    STATE_NAME,
    COUNTY_NAME,
    CATEGORY_NAME,
    FOREMAN_NAME,
    DATE_VALUE,
    VOLUME_MSCF,
    LATITUDE,
    LONGITUDE
 FROM 
FLARE_DATA
)
--
--
--
--
SELECT 
    '2019 VALUES' AS YEAR_CATEGORY,
    PROPERTY_NAME,
    PROPERTY_ID,
    BASIN_NAME,
    STATE_NAME,
    COUNTY_NAME,
    CATEGORY_NAME,
    FOREMAN_NAME,
    DATE_VALUE,
    VOLUME_MSCF,
    LATITUDE,
    LONGITUDE
 FROM 
FLARE
WHERE EXTRACT(YEAR FROM DATE_VALUE) = '2019'

UNION

SELECT 
    '2020 TARGET' AS YEAR_CATEGORY,
    PROPERTY_NAME,
    PROPERTY_ID,
    BASIN_NAME,
    STATE_NAME,
    COUNTY_NAME,
    CATEGORY_NAME,
    FOREMAN_NAME,
    ADD_MONTHS(DATE_VALUE,-48) AS DATE_VALUE,
    ROUND((VOLUME_MSCF*.92),1) AS VOLUME_MSCF,
    LATITUDE,
    LONGITUDE
 FROM 
FLARE
WHERE EXTRACT(YEAR FROM DATE_VALUE) = '2019'

UNION

SELECT 
    '2020 VALUES' AS YEAR_CATEGORY,
    PROPERTY_NAME,
    PROPERTY_ID,
    BASIN_NAME,
    STATE_NAME,
    COUNTY_NAME,
    CATEGORY_NAME,
    FOREMAN_NAME,
    DATE_VALUE,
    VOLUME_MSCF,
    LATITUDE,
    LONGITUDE
 FROM 
FLARE
WHERE EXTRACT(YEAR FROM DATE_VALUE) = '2020'

UNION

SELECT 
    '2020 VALUES' AS YEAR_CATEGORY,
    NULL AS  PROPERTY_NAME,
    NULL AS  PROPERTY_ID,
    'BASIN 1' AS BASIN_NAME,
    NULL AS STATE_NAME,
    NULL AS COUNTY_NAME,
    NULL AS CATEGORY_NAME,
    NULL AS FOREMAN_NAME,
     TO_DATE('01-JAN-2020 00:00:00', 'DD-MON-YYYY HH24:MI:SS') AS DATE_VALUE,
    0 VOLUME_MSCF,
    NULL AS LATITUDE,
    NULL AS LONGITUDE
 FROM 
DUAL

UNION

SELECT 
    '2020 VALUES' AS YEAR_CATEGORY,
    NULL AS  PROPERTY_NAME,
    NULL AS  PROPERTY_ID,
    'BASIN 2' AS BASIN_NAME,
    NULL AS STATE_NAME,
    NULL AS COUNTY_NAME,
    NULL AS CATEGORY_NAME,
    NULL AS FOREMAN_NAME,
     TO_DATE('01-JAN-2020 00:00:00', 'DD-MON-YYYY HH24:MI:SS') AS DATE_VALUE,
    0 VOLUME_MSCF,
    NULL AS LATITUDE,
    NULL AS LONGITUDE
 FROM 
DUAL

UNION

SELECT 
    '2018 VALUES' AS YEAR_CATEGORY,
    PROPERTY_NAME,
    PROPERTY_ID,
    BASIN_NAME,
    STATE_NAME,
    COUNTY_NAME,
    CATEGORY_NAME,
    FOREMAN_NAME,
    DATE_VALUE,
    VOLUME_MSCF,
    LATITUDE,
    LONGITUDE
 FROM 
FLARE
    WHERE EXTRACT(YEAR FROM DATE_VALUE) = '2018'
